name: Build Wheels for M1 Mac
on: 
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  build_wheels_macos:
    name: Build wheels on macos-10.15
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install MacOS dependencies
        run: |
          brew install libomp armadillo

      # Numpy 1.19 has an annoying issue with PyPy
      # See https://github.com/numpy/numpy/issues/15947
      - name: Fix Numpy for PyPy
        run: |
          brew install openblas
          pip uninstall numpy
          OPENBLAS="$(brew --prefix openblas)" pip install --ignore-installed --no-cache-dir numpy

      # Note: Only CPython 3.8 and newer support universal2 and arm64 wheels
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_BUILD: pp*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels_macos]
    runs-on: ubuntu-latest # Can only upload from Linux containers
    # TODO: RBF
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          # For PyPI
          # password: ${{ secrets.PYPI_APIKEY }}
          # For TestPyPI. TODO: RBF
          password: ${{ secrets.TEST_PYPI_APIKEY }}
          repository_url: https://test.pypi.org/legacy/