name: MacOS - build wheels
on: 
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  build_wheels_macos:
    name: Build wheels on macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install MacOS dependencies
        run: |
          brew install libomp armadillo

      # Note: CIBW only supports CPython 3.8 and newer for universal2 and arm64 wheels
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_BUILD: cp*
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels_macos]
    runs-on: ubuntu-latest # Can only upload from Linux containers
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Upload to TestPyPI on PR update
        if: ${{ github.event_name == 'pull_request' }}
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_APIKEY }}
          repository_url: https://test.pypi.org/legacy/

      - name: Upload to PyPI on published release
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_APIKEY }}