name: Build Wheels for M1 Mac
on: 
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  build_wheels_macos:
    name: Build wheels on macos-10.15
    runs-on: macos-10.15
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2

      # Is this necessary?
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # Is this necessary?
      - name: Install MacOS dependencies
        run: |
          brew install libomp armadillo

      # # Is this necessary?
      # - name: Install Python dependencies 
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Note: Only CPython 3.8 and newer support universal2 and arm64 wheels
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_MACOS: universal2 # x86_64 universal2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels_macos]
    runs-on: macos-10.15
    # TODO: RBF
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          # For PyPI
          # password: ${{ secrets.PYPI_APIKEY }}
          # For TestPyPI. TODO: RBF
          password: ${{ secrets.TEST_PYPI_APIKEY }}
          repository_url: https://test.pypi.org/legacy