name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
      - name: Install Armadillo 10.7.5+
        run: |
          cd ~
          git clone git clone https://gitlab.com/conradsnicta/armadillo-code.git
          cd armadillo-code
          sudo cmake .
          sudo make install
      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install carma
        run: |
          cd ~
          git clone https://github.com/RUrlus/carma.git
          cd carma
          mkdir build
          cd build
          sudo cmake -DCARMA_INSTALL_LIB=ON ..
          sudo cmake --build . --config Release --target install
          cd ~
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install BanditPAM package
        run: |
          pip install -vvv -e .
        
        # The default compiler on the Github Ubuntu runners is gcc
        # Would need to make a respective include change for clang 
        env:
          CPLUS_INCLUDE_PATH: /usr/local/include/carma
      - name: Run commit tests
        run: |
          pytest tests/test_commit.py 