name: MacOS - build package and run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # On the MacOS machine, when installing from source,
      # we use LLVM Clang
      - name: Install MacOS dependencies
        run: |
          brew install llvm libomp armadillo
          echo "BREW PREFIX:" && brew --prefix libomp
          echo "LIBOMP:" && ls -alh $(brew --prefix libomp)
          echo "DYLD_LIBRARY_PATH:$(DLYD_LIBRARY_PATH)"
          printenv
          gcc --version
          g++ --version
          clang --version
          clang++ --version

      - name: Install Python dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install Armadillo 10.7.5+
        run: |
          cd ~
          git clone https://gitlab.com/conradsnicta/armadillo-code.git
          cd armadillo-code
          sudo cmake .
          sudo make install

      - name: Install carma
        run: |
          cd ~
          git clone https://github.com/RUrlus/carma.git
          cd carma
          mkdir build
          cd build
          sudo cmake -DCARMA_INSTALL_LIB=ON ..
          sudo cmake --build . --config Release --target install
          cd ~

      - name: Install BanditPAM package
        run: |
          # The flags are necessary to ignore the pyproject.toml
          # See https://github.com/pypa/pip/issues/9738
          pip install --no-use-pep517 --no-build-isolation -vvv -e .
        env:
          # The default compiler on the Github Ubuntu runners is gcc
          # Would need to make a respective include change for clang 
          CPLUS_INCLUDE_PATH: /usr/local/include/carma:/usr/local/Cellar/libomp/15.0.2/include:/usr/local/Cellar/libomp/15.0.7/include

      - name: Downloading data files for tests
        run: |
          mkdir -p data
          curl -XGET https://motiwari.com/banditpam_data/scRNA_1k.csv > data/scRNA_1k.csv
          curl -XGET https://motiwari.com/banditpam_data/scrna_reformat.csv.gz > data/scrna_reformat.csv.gz
          curl -XGET https://motiwari.com/banditpam_data/MNIST_100.csv > data/MNIST_100.csv
          curl -XGET https://motiwari.com/banditpam_data/MNIST_1k.csv > data/MNIST_1k.csv
          curl -XGET https://motiwari.com/banditpam_data/MNIST_10k.tar.gz > data/MNIST_10k.tar.gz
          tar -xzvf data/MNIST_10k.tar.gz -C data
          curl -XGET https://motiwari.com/banditpam_data/MNIST_70k.tar.gz > data/MNIST_70k.tar.gz
          tar -xzvf data/MNIST_70k.tar.gz -C data

      - name: Run smaller suite of test cases
        run : |
          pytest tests/test_smaller.py 

      # - name: Run larger suite of test cases
      #   run : |
      #     pytest tests/test_larger.py 

      - name: Verify that the C++ executable compiles and runs
        run : |
          git clone https://github.com/ThrunGroup/BanditPAM
          cd BanditPAM
          mkdir build
          cd build
          sudo cmake ..
          sudo make
          src/BanditPAM -f ../data/MNIST_1k.csv -k 5 -l L2