name: Run style checks
on:
  push:
    branches:  # prevents running on tag push
      - '**'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install style check dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-format cppcheck

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest cpplint
          python -m pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --exclude headers/carma

      - name: Lint with clang-format
        uses: cpp-linter/cpp-linter-action@v2.6.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*'  # disable clang-tidy checks
          version: 16
          ignore: R_package  # TODO: remove this as part of #240
          files-changed-only: false

      - name: Exit if necessary
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1